version: "3.8"

services:
  # User Management API
  user-api:
    build: .
    container_name: kanizsa-user-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - kanizsa-users

  # Authentication Service
  auth-service:
    build: .
    container_name: kanizsa-auth-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - kanizsa-users

  # Authorization Service
  authorization-service:
    build: .
    container_name: kanizsa-authorization-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - kanizsa-users

  # Profile Service
  profile-service:
    build: .
    container_name: kanizsa-profile-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - kanizsa-users

  # Notification Service
  notification-service:
    build: .
    container_name: kanizsa-notification-service
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - kanizsa-users

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: kanizsa-users-db
    environment:
      - POSTGRES_DB=kanizsa_users
      - POSTGRES_USER=users_user
      - POSTGRES_PASSWORD=users_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kanizsa-users

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: kanizsa-users-redis
    environment:
      - REDIS_PASSWORD=redis_password
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - kanizsa-users

volumes:
  postgres_data:
  redis_data:

networks:
  kanizsa-users:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
